### ISSUE TITLE
wizard amigos certificate

### ISSUE THREAD

**Issue by ninabreznik** [wizardamigos/assets#1]
# @todo

- `@input` [brief screencast](https://watch.screencastify.com/v/5XCcYV4Y3qaSo3MwGpVe)
- `@input` [pinterest examples](https://www.pinterest.co.uk/zweidesign/certificates/)
- [ ] blank certificate of completion
  - [ ] text
  - [ ] design
  - [ ] wizardish font (use our existing from code camp page or find better)
  - [ ] should be printable to A4
  - [ ] should be able to manually add name of the participant, date and the title of the course

# @info 
- budget for up to 3h work

**Comment by ninabreznik** [comment]
Copy for the certificate

Title: `Certificate of Completion`

Body:
```
This certificate is awarded to 
<name>

for successful completion of 
<course>

and demonstrating an understanding of 
the basic concepts of <topic>

Wizard Amigos 
To learn beyond  the basics of  <topic>, visit WizardAmigos.com
```

Example:
```
name: Barbara Skuhala
course: The Basic Web Component Workshop
topic: Web Development
```
